default['win2016gen']['metadata']['copyright_holder'] = 'The Authors'
default['win2016gen']['metadata']['email'] = 'you@company.com'
# possible license values all_rights, apachev2, gplv2, gplv3, mit
default['win2016gen']['metadata']['license'] = 'apachev2'
default['win2016gen']['metadata']['git_org'] = 'https://github.com/yourcompany/'
default['win2016gen']['kitchen']['kitchen_gui'] = 'true'
default['win2016gen']['kitchen']['http_proxy'] = 'http://<username>@yourproxy:port'
default['win2016gen']['kitchen']['https_proxy'] = 'http://<username>@yourproxy:port'
default['win2016gen']['kitchen']['deprecations_errors'] = 'true'
default['win2016gen']['kitchen']['vagrant_username'] = 'vagrant'
default['win2016gen']['kitchen']['vagrant_password'] = 'vagrant'
default['win2016gen']['kitchen']['vm_name'] = 'windows2016min'
default['win2016gen']['kitchen']['custom_memory'] = '2000'
default['win2016gen']['kitchen']['private_ip'] = '192.168.33.33'
